# Generated by Django 5.1.5 on 2025-01-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="view_count",
            field=models.IntegerField(verbose_name="조회수"),
        ),
    ]
