# Generated by Django 5.1.5 on 2025-01-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_writer_alter_post_created_at_alter_post_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
    ]
